### ISSUE TITLE
RejectedExecutionException Occured in onMessage.

### ISSUE THREAD

**Issue by mypplication** [socketio/engine.io-client-java#53]
Same issue here > https://github.com/socketio/socket.io-client-java/issues/295

This bug is the result of how you use the OkHttpClient object. In version 3 of OkHttp, do not recreate the instance OkHttpClient each use in your code:

> [There is no longer a global singleton connection pool. In OkHttp 2.x, all OkHttpClient instances shared a common connection pool by default. In OkHttp 3.x, each new OkHttpClient gets its own private connection pool. Applications should avoid creating many connection pools as doing so prevents connection reuse. Each connection pool holds its own set of connections alive so applications that have many pools also risk exhausting memory!](https://github.com/square/okhttp/blob/master/CHANGELOG.md)

[https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/transports/WebSocket.java](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/transports/WebSocket.java)

**Comment by nkzawa** [comment]
Hi, thanks for your report. Let me know how to reproduce if possible.

**Comment by mypplication** [comment]
Hello, sorry but for the moment, i can't reproduce.. 
if you look pkHttp3 websocket implementation, you can see ThreadPoolExecutor if created with a pool size limited to 1
[https://github.com/square/okhttp/blob/master/okhttp-ws%2Fsrc%2Fmain%2Fjava%2Fokhttp3%2Fws%2FWebSocketCall.java#L162](https://github.com/square/okhttp/blob/master/okhttp-ws%2Fsrc%2Fmain%2Fjava%2Fokhttp3%2Fws%2FWebSocketCall.java#L162)
I think is the source of this issue

**Comment by dusanvita** [comment]
Hi, I'm experiencing the same exception, but in onClose(), not onMessage() of RealWebSocket's reader implementation because ThreadPoolExecutor (replyExecutor) is not at all used in onMessage() but in on onPing() and onClose(). My only assumption is that ping response runner is already in the pool at the point of onClose request from the server so it throws an exception since it can only have one runner at the time.

This issue definitely is occurring while using engine.io/socket.io but I rather think it is in the OkHttp library itself and not here...

**Comment by shobhitpuri** [comment]
Just saw this thread after creating the issue https://github.com/socketio/engine.io-client-java/issues/81 . I think what @mypplication said contributes to Out of Memory exceptions as well as mentioned there.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
